version: '3.8'

services:
  frontend:
    build:
      context: ./front/my-app
      dockerfile: Dockerfile
    container_name: frontend
    restart: always

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend
    restart: always

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  db-data:
